package com.valhol.SolstCodeExam.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.valhol.SolstCodeExam.dao.Contact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTACT".
*/
public class ContactDao extends AbstractDao<Contact, Long> {

    public static final String TABLENAME = "CONTACT";

    /**
     * Properties of entity Contact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property EmployeeId = new Property(2, Long.class, "employeeId", false, "EMPLOYEE_ID");
        public final static Property Company = new Property(3, String.class, "company", false, "COMPANY");
        public final static Property DetailsURL = new Property(4, String.class, "detailsURL", false, "DETAILS_URL");
        public final static Property SmallImageURL = new Property(5, String.class, "smallImageURL", false, "SMALL_IMAGE_URL");
        public final static Property Birthdate = new Property(6, String.class, "birthdate", false, "BIRTHDATE");
        public final static Property PhonesId = new Property(7, Long.class, "phonesId", false, "PHONES_ID");
        public final static Property ContactDetailsId = new Property(8, Long.class, "contactDetailsId", false, "CONTACT_DETAILS_ID");
    };

    private DaoSession daoSession;


    public ContactDao(DaoConfig config) {
        super(config);
    }
    
    public ContactDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTACT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"EMPLOYEE_ID\" INTEGER UNIQUE ," + // 2: employeeId
                "\"COMPANY\" TEXT," + // 3: company
                "\"DETAILS_URL\" TEXT," + // 4: detailsURL
                "\"SMALL_IMAGE_URL\" TEXT," + // 5: smallImageURL
                "\"BIRTHDATE\" TEXT," + // 6: birthdate
                "\"PHONES_ID\" INTEGER," + // 7: phonesId
                "\"CONTACT_DETAILS_ID\" INTEGER);"); // 8: contactDetailsId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTACT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Contact entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        Long employeeId = entity.getEmployeeId();
        if (employeeId != null) {
            stmt.bindLong(3, employeeId);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(4, company);
        }
 
        String detailsURL = entity.getDetailsURL();
        if (detailsURL != null) {
            stmt.bindString(5, detailsURL);
        }
 
        String smallImageURL = entity.getSmallImageURL();
        if (smallImageURL != null) {
            stmt.bindString(6, smallImageURL);
        }
 
        String birthdate = entity.getBirthdate();
        if (birthdate != null) {
            stmt.bindString(7, birthdate);
        }
 
        Long phonesId = entity.getPhonesId();
        if (phonesId != null) {
            stmt.bindLong(8, phonesId);
        }
 
        Long contactDetailsId = entity.getContactDetailsId();
        if (contactDetailsId != null) {
            stmt.bindLong(9, contactDetailsId);
        }
    }

    @Override
    protected void attachEntity(Contact entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Contact readEntity(Cursor cursor, int offset) {
        Contact entity = new Contact( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // employeeId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // company
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // detailsURL
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // smallImageURL
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // birthdate
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // phonesId
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // contactDetailsId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Contact entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEmployeeId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setCompany(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDetailsURL(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSmallImageURL(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBirthdate(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPhonesId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setContactDetailsId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Contact entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Contact entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPhoneDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getContactDetailsDao().getAllColumns());
            builder.append(" FROM CONTACT T");
            builder.append(" LEFT JOIN PHONE T0 ON T.\"PHONES_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN CONTACT_DETAILS T1 ON T.\"CONTACT_DETAILS_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Contact loadCurrentDeep(Cursor cursor, boolean lock) {
        Contact entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Phone phone = loadCurrentOther(daoSession.getPhoneDao(), cursor, offset);
        entity.setPhone(phone);
        offset += daoSession.getPhoneDao().getAllColumns().length;

        ContactDetails contactDetails = loadCurrentOther(daoSession.getContactDetailsDao(), cursor, offset);
        entity.setContactDetails(contactDetails);

        return entity;    
    }

    public Contact loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Contact> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Contact> list = new ArrayList<Contact>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Contact> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Contact> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
